INSERT INTO user (
        email,
        username,
        password,
        user_role
    )
VALUES (
        'admin@a.com',
        'admin',
        'admin',
        'ADMIN'
    ),
    (
        'dave@a.com',
        'dave',
        'dave',
        'CUSTOMER'
    ),
    (
        'rick@a.com',
        'rick',
        'rick',
        'CUSTOMER'
    ),
    (
        'peter@a.com',
        'Peter',
        '123',
        'ADMIN'
    );