DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INTEGER(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(45) NOT NULL,
    user_role VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    password VARCHAR(64) NOT NULL
);